import 'package:app/data_provider/clients_data_provider.dart';
import 'package:app/models/client.dart';

class ClientsRepository {
  final ClientsDataProvider clientsDataProvider;
  ClientsRepository({required this.clientsDataProvider});

  Future<ClientAutogenerated> getClients(int page) async {
    ClientAutogenerated data = await clientsDataProvider.getClients(page);
    print("Data arrived at the data provider $data");
    return data;
  }

  Future<void> createClient(CreateClientData data) async {
    return await clientsDataProvider.createClient(data);
  }
}
